<?php

namespace Database\Seeders;

use App\Models\Currency;
// use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class CurrencySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        Currency::updateOrCreate(
            ['symbol' => 'USD'], // Kriteria pencarian
            [
                'name' => 'US Dollar',
                'currency_type' => 'fiat', // Pastikan ini sesuai dengan nama kolom di DB Anda
            ]
        );

        $cryptocurrencies = [
            ['name' => 'Bitcoin', 'symbol' => 'BTC', 'currency_type' => 'crypto'],
            ['name' => 'Ethereum', 'symbol' => 'ETH', 'currency_type' => 'crypto'],
            ['name' => 'Tether', 'symbol' => 'USDT', 'currency_type' => 'crypto'],
            ['name' => 'BNB', 'symbol' => 'BNB', 'currency_type' => 'crypto'],
            ['name' => 'Solana', 'symbol' => 'SOL', 'currency_type' => 'crypto'],
            ['name' => 'USDC', 'symbol' => 'USDC', 'currency_type' => 'crypto'],
            ['name' => 'XRP', 'symbol' => 'XRP', 'currency_type' => 'crypto'],
            ['name' => 'Dogecoin', 'symbol' => 'DOGE', 'currency_type' => 'crypto'],
            ['name' => 'Toncoin', 'symbol' => 'TON', 'currency_type' => 'crypto'],
            ['name' => 'Cardano', 'symbol' => 'ADA', 'currency_type' => 'crypto'],
            ['name' => 'Shiba Inu', 'symbol' => 'SHIB', 'currency_type' => 'crypto'],
            ['name' => 'Avalanche', 'symbol' => 'AVAX', 'currency_type' => 'crypto'],
            ['name' => 'Polkadot', 'symbol' => 'DOT', 'currency_type' => 'crypto'],
            ['name' => 'TRON', 'symbol' => 'TRX', 'currency_type' => 'crypto'],
            ['name' => 'Chainlink', 'symbol' => 'LINK', 'currency_type' => 'crypto'],
            ['name' => 'Polygon', 'symbol' => 'MATIC', 'currency_type' => 'crypto'],
            ['name' => 'Bitcoin Cash', 'symbol' => 'BCH', 'currency_type' => 'crypto'],
            ['name' => 'Uniswap', 'symbol' => 'UNI', 'currency_type' => 'crypto'],
            ['name' => 'NEAR Protocol', 'symbol' => 'NEAR', 'currency_type' => 'crypto'],
            ['name' => 'Litecoin', 'symbol' => 'LTC', 'currency_type' => 'crypto'],
            ['name' => 'Internet Computer', 'symbol' => 'ICP', 'currency_type' => 'crypto'],
            ['name' => 'Dai', 'symbol' => 'DAI', 'currency_type' => 'crypto'],
            ['name' => 'LEO Token', 'symbol' => 'LEO', 'currency_type' => 'crypto'],
            ['name' => 'Ethereum Classic', 'symbol' => 'ETC', 'currency_type' => 'crypto'],
            ['name' => 'Stacks', 'symbol' => 'STX', 'currency_type' => 'crypto'],
            ['name' => 'Filecoin', 'symbol' => 'FIL', 'currency_type' => 'crypto'],
            ['name' => 'Cosmos', 'symbol' => 'ATOM', 'currency_type' => 'crypto'],
            ['name' => 'Cronos', 'symbol' => 'CRO', 'currency_type' => 'crypto'],
            ['name' => 'Aptos', 'symbol' => 'APT', 'currency_type' => 'crypto'],
            ['name' => 'Hedera', 'symbol' => 'HBAR', 'currency_type' => 'crypto'],
            ['name' => 'VeChain', 'symbol' => 'VET', 'currency_type' => 'crypto'],
            ['name' => 'Monero', 'symbol' => 'XMR', 'currency_type' => 'crypto'],
            ['name' => 'Mantle', 'symbol' => 'MNT', 'currency_type' => 'crypto'],
            ['name' => 'Arbitrum', 'symbol' => 'ARB', 'currency_type' => 'crypto'],
            ['name' => 'Optimism', 'symbol' => 'OP', 'currency_type' => 'crypto'],
            ['name' => 'Kaspa', 'symbol' => 'KAS', 'currency_type' => 'crypto'],
            ['name' => 'Bittensor', 'symbol' => 'TAO', 'currency_type' => 'crypto'],
            ['name' => 'Stellar', 'symbol' => 'XLM', 'currency_type' => 'crypto'],
            ['name' => 'OKB', 'symbol' => 'OKB', 'currency_type' => 'crypto'],
            ['name' => 'Injective', 'symbol' => 'INJ', 'currency_type' => 'crypto'],
            ['name' => 'Immutable', 'symbol' => 'IMX', 'currency_type' => 'crypto'],
            ['name' => 'Lido DAO', 'symbol' => 'LDO', 'currency_type' => 'crypto'],
            ['name' => 'Render', 'symbol' => 'RNDR', 'currency_type' => 'crypto'],
            ['name' => 'Holo', 'symbol' => 'HOT', 'currency_type' => 'crypto'],
            ['name' => 'The Graph', 'symbol' => 'GRT', 'currency_type' => 'crypto'],
            ['name' => 'Theta Network', 'symbol' => 'THETA', 'currency_type' => 'crypto'],
            ['name' => 'Celestia', 'symbol' => 'TIA', 'currency_type' => 'crypto'],
            ['name' => 'First Digital USD', 'symbol' => 'FDUSD', 'currency_type' => 'crypto'],
            ['name' => 'Pepe', 'symbol' => 'PEPE', 'currency_type' => 'crypto'],
            ['name' => 'Sui', 'symbol' => 'SUI', 'currency_type' => 'crypto'],
            ['name' => 'Maker', 'symbol' => 'MKR', 'currency_type' => 'crypto'],
            ['name' => 'Fantom', 'symbol' => 'FTM', 'currency_type' => 'crypto'],
            ['name' => 'Rocket Pool', 'symbol' => 'RPL', 'currency_type' => 'crypto'],
            ['name' => 'THORChain', 'symbol' => 'RUNE', 'currency_type' => 'crypto'],
            ['name' => 'Algorand', 'symbol' => 'ALGO', 'currency_type' => 'crypto'],
            ['name' => 'Mina', 'symbol' => 'MINA', 'currency_type' => 'crypto'],
            ['name' => 'Flow', 'symbol' => 'FLOW', 'currency_type' => 'crypto'],
            ['name' => 'Aave', 'symbol' => 'AAVE', 'currency_type' => 'crypto'],
            ['name' => 'Sei', 'symbol' => 'SEI', 'currency_type' => 'crypto'],
            ['name' => 'Quant', 'symbol' => 'QNT', 'currency_type' => 'crypto'],
            ['name' => 'Beam', 'symbol' => 'BEAM', 'currency_type' => 'crypto'],
            ['name' => 'Bitcoin SV', 'symbol' => 'BSV', 'currency_type' => 'crypto'],
            ['name' => 'MultiversX', 'symbol' => 'EGLD', 'currency_type' => 'crypto'],
            ['name' => 'Conflux', 'symbol' => 'CFX', 'currency_type' => 'crypto'],
            ['name' => 'dYdX', 'symbol' => 'DYDX', 'currency_type' => 'crypto'],
            ['name' => 'ORDI', 'symbol' => 'ORDI', 'currency_type' => 'crypto'],
            ['name' => 'Flare', 'symbol' => 'FLR', 'currency_type' => 'crypto'],
            ['name' => 'Axie Infinity', 'symbol' => 'AXS', 'currency_type' => 'crypto'],
            ['name' => 'Synthetix', 'symbol' => 'SNX', 'currency_type' => 'crypto'],
            ['name' => 'Tezos', 'symbol' => 'XTZ', 'currency_type' => 'crypto'],
            ['name' => 'Chiliz', 'symbol' => 'CHZ', 'currency_type' => 'crypto'],
            ['name' => 'Worldcoin', 'symbol' => 'WLD', 'currency_type' => 'crypto'],
            ['name' => 'KuCoin Token', 'symbol' => 'KCS', 'currency_type' => 'crypto'],
            ['name' => 'EOS', 'symbol' => 'EOS', 'currency_type' => 'crypto'],
            ['name' => 'Tokenize Xchange', 'symbol' => 'TKX', 'currency_type' => 'crypto'],
            ['name' => 'NEO', 'symbol' => 'NEO', 'currency_type' => 'crypto'],
            ['name' => 'BitTorrent', 'symbol' => 'BTT', 'currency_type' => 'crypto'],
            ['name' => 'Decentraland', 'symbol' => 'MANA', 'currency_type' => 'crypto'],
            ['name' => 'Osmosis', 'symbol' => 'OSMO', 'currency_type' => 'crypto'],
            ['name' => 'Bonk', 'symbol' => 'BONK', 'currency_type' => 'crypto'],
            ['name' => 'GALA', 'symbol' => 'GALA', 'currency_type' => 'crypto'],
            ['name' => 'JasmyCoin', 'symbol' => 'JASMY', 'currency_type' => 'crypto'],
            ['name' => 'FLOKI', 'symbol' => 'FLOKI', 'currency_type' => 'crypto'],
            ['name' => 'IOTA', 'symbol' => 'IOTA', 'currency_type' => 'crypto'],
            ['name' => 'Akash Network', 'symbol' => 'AKT', 'currency_type' => 'crypto'],
            ['name' => 'Astar', 'symbol' => 'ASTR', 'currency_type' => 'crypto'],
            ['name' => 'PancakeSwap', 'symbol' => 'CAKE', 'currency_type' => 'crypto'],
            ['name' => 'WOO Network', 'symbol' => 'WOO', 'currency_type' => 'crypto'],
            ['name' => 'Klaytn', 'symbol' => 'KLAY', 'currency_type' => 'crypto'],
            ['name' => 'Bitget Token', 'symbol' => 'BGB', 'currency_type' => 'crypto'],
            ['name' => 'Fetch.ai', 'symbol' => 'FET', 'currency_type' => 'crypto'],
            ['name' => 'Ronin', 'symbol' => 'RON', 'currency_type' => 'crypto'],
            ['name' => 'eCash', 'symbol' => 'XEC', 'currency_type' => 'crypto'],
            ['name' => 'Terra Classic', 'symbol' => 'LUNC', 'currency_type' => 'crypto'],
            ['name' => 'SingularityNET', 'symbol' => 'AGIX', 'currency_type' => 'crypto'],
            ['name' => 'dYdX (Native)', 'symbol' => 'ETHDYDX', 'currency_type' => 'crypto'],
            ['name' => 'Marinade staked SOL', 'symbol' => 'MSOL', 'currency_type' => 'crypto'],
            ['name' => 'USDD', 'symbol' => 'USDD', 'currency_type' => 'crypto'],
            ['name' => 'Gnosis', 'symbol' => 'GNO', 'currency_type' => 'crypto'],
            ['name' => 'SATS', 'symbol' => 'SATS', 'currency_type' => 'crypto'],
            ['name' => 'Oasis Network', 'symbol' => 'ROSE', 'currency_type' => 'crypto'],
            ['name' => 'Kava', 'symbol' => 'KAVA', 'currency_type' => 'crypto'],
            ['name' => 'Pyth Network', 'symbol' => 'PYTH', 'currency_type' => 'crypto'],
            ['name' => 'Kusama', 'symbol' => 'KSM', 'currency_type' => 'crypto'],
            ['name' => 'Nervos Network', 'symbol' => 'CKB', 'currency_type' => 'crypto'],
            ['name' => 'Tether Gold', 'symbol' => 'XAUT', 'currency_type' => 'crypto'],
            ['name' => 'IoTeX', 'symbol' => 'IOTX', 'currency_type' => 'crypto'],
            ['name' => 'Celo', 'symbol' => 'CELO', 'currency_type' => 'crypto'],
            ['name' => 'WEMIX', 'symbol' => 'WEMIX', 'currency_type' => 'crypto'],
            ['name' => 'Ethereum Name Service', 'symbol' => 'ENS', 'currency_type' => 'crypto'],
            ['name' => 'Core', 'symbol' => 'CORE', 'currency_type' => 'crypto'],
            ['name' => 'Manta Network', 'symbol' => 'MANTA', 'currency_type' => 'crypto'],
            ['name' => 'Illuvium', 'symbol' => 'ILV', 'currency_type' => 'crypto'],
            ['name' => 'Golem', 'symbol' => 'GLM', 'currency_type' => 'crypto'],
            ['name' => '1inch Network', 'symbol' => '1INCH', 'currency_type' => 'crypto'],
            ['name' => 'PAX Gold', 'symbol' => 'PAXG', 'currency_type' => 'crypto'],
            ['name' => 'Radix', 'symbol' => 'XRD', 'currency_type' => 'crypto'],
            ['name' => 'Zilliqa', 'symbol' => 'ZIL', 'currency_type' => 'crypto'],
            ['name' => 'Compound', 'symbol' => 'COMP', 'currency_type' => 'crypto'],
            ['name' => 'Ankr', 'symbol' => 'ANKR', 'currency_type' => 'crypto'],
            ['name' => 'Moonbeam', 'symbol' => 'GLMR', 'currency_type' => 'crypto'],
            ['name' => 'Metis', 'symbol' => 'METIS', 'currency_type' => 'crypto'],
            ['name' => 'ApeCoin', 'symbol' => 'APE', 'currency_type' => 'crypto'],
            ['name' => 'Decred', 'symbol' => 'DCR', 'currency_type' => 'crypto'],
            ['name' => 'GMX', 'symbol' => 'GMX', 'currency_type' => 'crypto'],
            ['name' => 'Lisk', 'symbol' => 'LSK', 'currency_type' => 'crypto'],
            ['name' => 'Ocean Protocol', 'symbol' => 'OCEAN', 'currency_type' => 'crypto'],
            ['name' => 'SKALE', 'symbol' => 'SKL', 'currency_type' => 'crypto'],
            ['name' => 'Terra', 'symbol' => 'LUNA', 'currency_type' => 'crypto'],
            ['name' => 'Pendle', 'symbol' => 'PENDLE', 'currency_type' => 'crypto'],
            ['name' => 'Stratis', 'symbol' => 'STRAX', 'currency_type' => 'crypto'],
            ['name' => 'Sushi', 'symbol' => 'SUSHI', 'currency_type' => 'crypto'],
            ['name' => 'NEM', 'symbol' => 'XEM', 'currency_type' => 'crypto'],
            ['name' => 'Starknet', 'symbol' => 'STRK', 'currency_type' => 'crypto'],
            ['name' => 'Arweave', 'symbol' => 'AR', 'currency_type' => 'crypto'],
            ['name' => 'Basic Attention Token', 'symbol' => 'BAT', 'currency_type' => 'crypto'],
            ['name' => 'Enjin Coin', 'symbol' => 'ENJ', 'currency_type' => 'crypto'],
            ['name' => 'Loopring', 'symbol' => 'LRC', 'currency_type' => 'crypto'],
            ['name' => 'CorgiAI', 'symbol' => 'CORGIAI', 'currency_type' => 'crypto'],
            ['name' => 'Qtum', 'symbol' => 'QTUM', 'currency_type' => 'crypto'],
            ['name' => 'Ravencoin', 'symbol' => 'RVN', 'currency_type' => 'crypto'],
            ['name' => 'Dymension', 'symbol' => 'DYM', 'currency_type' => 'crypto'],
            ['name' => 'API3', 'symbol' => 'API3', 'currency_type' => 'crypto'],
            ['name' => 'Echelon Prime', 'symbol' => 'PRIME', 'currency_type' => 'crypto'],
            ['name' => 'Livepeer', 'symbol' => 'LPT', 'currency_type' => 'crypto'],
            ['name' => 'Mina Protocol', 'symbol' => 'MINA', 'currency_type' => 'crypto'],
            ['name' => 'Convex Finance', 'symbol' => 'CVX', 'currency_type' => 'crypto'],
            ['name' => 'Polymath', 'symbol' => 'POLY', 'currency_type' => 'crypto'],
            ['name' => 'Blur', 'symbol' => 'BLUR', 'currency_type' => 'crypto'],
            ['name' => 'Moonriver', 'symbol' => 'MOVR', 'currency_type' => 'crypto'],
            ['name' => 'MX TOKEN', 'symbol' => 'MX', 'currency_type' => 'crypto'],
            ['name' => 'Gas', 'symbol' => 'GAS', 'currency_type' => 'crypto'],
            ['name' => 'OriginTrail', 'symbol' => 'TRAC', 'currency_type' => 'crypto'],
            ['name' => 'Pixels', 'symbol' => 'PIXEL', 'currency_type' => 'crypto'],
            ['name' => 'aelf', 'symbol' => 'ELF', 'currency_type' => 'crypto'],
            ['name' => 'WAX', 'symbol' => 'WAXP', 'currency_type' => 'crypto'],
            ['name' => 'TomoChain', 'symbol' => 'TOMO', 'currency_type' => 'crypto'],
            ['name' => 'Reserve Rights', 'symbol' => 'RSR', 'currency_type' => 'crypto'],
            ['name' => 'Ontology', 'symbol' => 'ONT', 'currency_type' => 'crypto'],
            ['name' => 'Nexo', 'symbol' => 'NEXO', 'currency_type' => 'crypto'],
            ['name' => 'Jupiter', 'symbol' => 'JUP', 'currency_type' => 'crypto'],
            ['name' => 'ICON', 'symbol' => 'ICX', 'currency_type' => 'crypto'],
            ['name' => 'Chromia', 'symbol' => 'CHR', 'currency_type' => 'crypto'],
            ['name' => 'Frax Share', 'symbol' => 'FXS', 'currency_type' => 'crypto'],
            ['name' => 'DAO Maker', 'symbol' => 'DAO', 'currency_type' => 'crypto'],
            ['name' => 'DigiByte', 'symbol' => 'DGB', 'currency_type' => 'crypto'],
            ['name' => 'Swipe', 'symbol' => 'SXP', 'currency_type' => 'crypto'],
            ['name' => 'Syntropy', 'symbol' => 'NOIA', 'currency_type' => 'crypto'],
            ['name' => 'Venom', 'symbol' => 'VENOM', 'currency_type' => 'crypto'],
            ['name' => 'Biconomy', 'symbol' => 'BICO', 'currency_type' => 'crypto'],
            ['name' => 'Band Protocol', 'symbol' => 'BAND', 'currency_type' => 'crypto'],
            ['name' => 'Alchemy Pay', 'symbol' => 'ACH', 'currency_type' => 'crypto'],
            ['name' => 'Aragon', 'symbol' => 'ANT', 'currency_type' => 'crypto'],
            ['name' => 'Harmony', 'symbol' => 'ONE', 'currency_type' => 'crypto'],
            ['name' => 'iExec RLC', 'symbol' => 'RLC', 'currency_type' => 'crypto'],
            ['name' => 'MAGIC', 'symbol' => 'MAGIC', 'currency_type' => 'crypto'],
            ['name' => 'Telcoin', 'symbol' => 'TEL', 'currency_type' => 'crypto'],
            ['name' => 'Ribbon Finance', 'symbol' => 'RBN', 'currency_type' => 'crypto'],
            ['name' => 'Audius', 'symbol' => 'AUDIO', 'currency_type' => 'crypto'],
            ['name' => 'EthereumPoW', 'symbol' => 'ETHW', 'currency_type' => 'crypto'],
            ['name' => 'Moonrock Capital', 'symbol' => 'ROCK', 'currency_type' => 'crypto'],
            ['name' => 'Cartesi', 'symbol' => 'CTSI', 'currency_type' => 'crypto'],
            ['name' => 'NuCypher', 'symbol' => 'NU', 'currency_type' => 'crypto'],
            ['name' => 'Coin98', 'symbol' => 'C98', 'currency_type' => 'crypto'],
            ['name' => 'SuperVerse', 'symbol' => 'SUPER', 'currency_type' => 'crypto'],
            ['name' => 'Vulcan Forged PYR', 'symbol' => 'PYR', 'currency_type' => 'crypto'],
            ['name' => 'Syscoin', 'symbol' => 'SYS', 'currency_type' => 'crypto'],
            ['name' => 'Dogelon Mars', 'symbol' => 'ELON', 'currency_type' => 'crypto'],
            ['name' => 'Hifi Finance', 'symbol' => 'MFT', 'currency_type' => 'crypto'],
            ['name' => 'Storj', 'symbol' => 'STORJ', 'currency_type' => 'crypto'],
            ['name' => 'Myro', 'symbol' => 'MYRO', 'currency_type' => 'crypto'],
            ['name' => 'Amp', 'symbol' => 'AMP', 'currency_type' => 'crypto'],
            ['name' => 'Escoin', 'symbol' => 'ELG', 'currency_type' => 'crypto'],
            ['name' => 'Wanchain', 'symbol' => 'WAN', 'currency_type' => 'crypto'],
            ['name' => 'Helium Mobile', 'symbol' => 'MOBILE', 'currency_type' => 'crypto'],
            ['name' => 'Dent', 'symbol' => 'DENT', 'currency_type' => 'crypto'],
            ['name' => 'Smooth Love Potion', 'symbol' => 'SLP', 'currency_type' => 'crypto'],
            ['name' => 'Ecoin', 'symbol' => 'ECOIN', 'currency_type' => 'crypto'],
            ['name' => 'Power Ledger', 'symbol' => 'POWR', 'currency_type' => 'crypto'],
            ['name' => 'SafePal', 'symbol' => 'SFP', 'currency_type' => 'crypto'],
            ['name' => 'Blox', 'symbol' => 'CDT', 'currency_type' => 'crypto'],
            ['name' => 'Galxe', 'symbol' => 'GAL', 'currency_type' => 'crypto'],
            ['name' => 'Meme Kombat', 'symbol' => 'MK', 'currency_type' => 'crypto'],
            ['name' => 'Degen', 'symbol' => 'DEGEN', 'currency_type' => 'crypto'],
            ['name' => 'MANTRA', 'symbol' => 'OM', 'currency_type' => 'crypto'],
            ['name' => 'Popcat', 'symbol' => 'POPCAT', 'currency_type' => 'crypto'],
        ];

        foreach ($cryptocurrencies as $currencyData) {
            Currency::updateOrCreate(
                ['symbol' => $currencyData['symbol']],
                [
                    'name' => $currencyData['name'],
                    'currency_type' => $currencyData['currency_type'],
                ]
            );
        }
    }
}
